# .github/workflows/workflow.yml

name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for Trusted Publishing
  contents: read   # Required to read the release

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No password/token needed — OIDC handles authentication
        verify-metadata: true
